export const languageMap = {
  "zh-cn": { name: "简体中文（中国大陆）", mark: "中文(大陆）" },
  "zh-tw": { name: "繁體中文（中國臺灣）", mark: "中文(台湾)" },
  "zh-hk": { name: "繁體中文（中國香港）", mark: "中文(香港)" },
  en: { name: "English", mark: "英语" },
  ja: { name: "日本語", mark: "日语" },
  ko: { name: "한국어", mark: "朝鲜语" },
  th: { name: "ภาษาไทย", mark: "泰语" },
  vi: { name: "ViệtName", mark: "越南语" },
  hi: { name: "हिन्दी", mark: "北印度语" },
  fr: { name: "Français", mark: "法语" },
  de: { name: "Deutsch", mark: "德语" },
  es: { name: "Español", mark: "西班牙语" },
  ru: { name: "русский язык", mark: "俄语" },
  "ar-sa": { name: "عربي ،", mark: "阿拉伯语" },
  nl: { name: "Nederlands", mark: "荷兰语" },
  it: { name: "Italiano", mark: "意大利语" },
  da: { name: "Dansk", mark: "丹麦语" },
  fi: { name: "Suomi", mark: "芬兰语" },
  el: { name: "Ελληνικά", mark: "希腊语" },
  pl: { name: "Polski", mark: "波兰语" },
  pt: { name: "Português", mark: "葡萄牙语" },
};

export default [
  { name: "简体中文（中国大陆）", code: "zh-cn", mark: "中文" },
  { name: "繁體中文（中國臺灣）", code: "zh-tw", mark: "中文" },
  { name: "繁體中文（中國香港）", code: "zh-hk", mark: "中文" },
  { name: "English", code: "en", mark: "英语" },
  { name: "日本語", code: "ja", mark: "日语" },
  { name: "한국어", code: "ko", mark: "朝鲜语" },
  { name: "ภาษาไทย", code: "th", mark: "泰语" },
  { name: "ViệtName", code: "vi", mark: "越南语" },
  { name: "हिन्दी", code: "hi", mark: "北印度语" },
  { name: "Français", code: "fr", mark: "法语" },
  { name: "Deutsch", code: "de", mark: "德语" },
  { name: "Español", code: "es", mark: "西班牙语" },
  { name: "русский язык", code: "ru", mark: "俄语" },
  { name: "عربي ،", code: "ar-sa", mark: "阿拉伯语" },
  { name: "Nederlands", code: "nl", mark: "荷兰语" },
  { name: "Italiano", code: "it", mark: "意大利语" },
  { name: "Dansk", code: "da", mark: "丹麦语" },
  { name: "Suomi", code: "fi", mark: "芬兰语" },
  { name: "Ελληνικά", code: "el", mark: "希腊语" },
  { name: "Polski", code: "pl", mark: "波兰语" },
  { name: "Português", code: "pt", mark: "葡萄牙语" },
];
